import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthTokenBridge from "./_auth-bridge"; // ← AJOUT

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthTokenBridge /> {/* ← AJOUT : écoute globale Supabase */}
        <header style={{padding:12,borderBottom:'1px solid #eee'}}>
          <nav style={{display:'flex',gap:12}}>
            <a href="/">Accueil</a>
            <a href="/recipes">📜 Mes recettes</a>
            <a href="/recipes/new">➕ Nouvelle recette</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
